### ISSUE TITLE
different base paths for different templates

### ISSUE THREAD

**Issue by magicspon** [FrancisVega/komp#1]
Hello,

Would it be possible to do something like this?

`komp new button --template fractal --basePath objects`

which would create a new button and output to 
./objects/

`komp new card --template fractal --basePath components`

which would create a new card and output to 
./components/

Cheers

**Comment by FrancisVega** [comment]
Hi,

You could use something like this:

`komp new ./objects/button --template fractal`

**Comment by magicspon** [comment]
aces.... 

on a different note... 

Is this available anywhere? https://vimeo.com/209467146

looks super impressive.

ta
